Question 1 :- What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code and functionalities that can be imported and used in Python programs to perform specific tasks without the need to write the code from scratch. These libraries typically contain functions, classes, and modules that offer solutions for common problems or provide tools to streamline development in various domains.

We use Python libraries for several reasons:
1. Efficiency: Libraries save time and effort by providing ready-made solutions to common programming problems.
2. Functionality: Libraries extend the capabilities of Python by offering a wide range of functionalities that aren't available in the core Python language.
3. Specialization: Many Python libraries are specialized for specific tasks or domains. For example, there are libraries for web development (e.g., Flask, Django).

Question 2 :- What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store collections of data, but they have several key differences in terms of functionality, performance, and usage :
1. Memory Efficiency:

NumPy arrays are more memory efficient compared to Python lists. This efficiency comes from NumPy arrays being homogeneous (all elements are of the same data type) and stored in contiguous memory blocks, while Python lists are heterogeneous and store references to objects in memory, leading to more overhead.

2. Performance:

* NumPy arrays generally offer better performance for numerical computations compared to Python lists. NumPy's underlying implementations are written in C, which allows for optimized operations and vectorized calculations.
* Python lists are more flexible but slower, especially for large datasets and numerical computations.

3. Functionality:

* NumPy arrays come with a wide range of mathematical functions and operations optimized for numerical computing, such as element-wise operations, linear algebra operations, statistical functions, and random number generation.
* Python lists provide more general-purpose functionality and are suitable for storing heterogeneous data types and performing basic list operations like appending, slicing, and concatenating.

Question 3 :- ind the shape, size and dimension of the following array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [9]:
import numpy as np

array = [[1, 2, 3, 4],

         [5, 6, 7, 8],

         [9, 10, 11, 12]]

np_array = np.array(array)

shape = np_array.shape

size = np_array.size

dimension = np_array.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


Question 4 :- Write python code to access the first row of the following array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]



In [11]:
import numpy as np

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)

first_row = np_array[0]

print("First row:", first_row)

First row: [1 2 3 4]


Question 5 :- How do you access the element at the third row and fourth column from the given numpy array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [13]:
import numpy as np 

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)

ele = np_array[2][3]
print("Element at the third row and fourth column:", ele)

Element at the third row and fourth column: 12


Question 6 :- Write code to extract all odd-indexed elements from the given numpy array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [14]:
import numpy as np

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)

odd_indexed_elements = np_array[:, 1::2]

print("Odd-indexed elements:", odd_indexed_elements)

Odd-indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


Question 7 :- How can you generate a random 3x3 matrix with values between 0 and 1?

In [15]:
import numpy as np 

random_matrix = np.random.random((3,3))

random_matrix

array([[0.98375057, 0.88886395, 0.73970583],
       [0.1547384 , 0.10273688, 0.47610656],
       [0.27365264, 0.59662568, 0.77788484]])

Question 8 :- Describe the difference between np.random.rand and np.random.randn?

1. np.random.rand:

This function generates random numbers from a uniform distribution over the range [0, 1), where each value has an equal probability of being selected.
You can specify the shape of the output array as arguments to the function.
For example, np.random.rand(3, 3) will generate a 3x3 array of random numbers between 0 and 1.

2. np.random.randn:

This function generates random numbers from a standard normal distribution (Gaussian distribution) with mean 0 and standard deviation 1.
The shape of the output array can also be specified as arguments to the function.
Unlike np.random.rand, you do not provide the range for the random numbers; they are drawn from a Gaussian distribution centered around 0.
For example, np.random.randn(3, 3) will generate a 3x3 array of random numbers sampled from a standard normal distribution.

Question 9 :- Write code to increase the dimension of the following array?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [17]:
import numpy as np

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)

expanded_array = np.expand_dims(np_array, axis=0)

print("Original array shape:", np_array.shape)
print("Expanded array shape:", expanded_array.shape)
print("Expanded array:")
print(expanded_array)

Original array shape: (3, 4)
Expanded array shape: (1, 3, 4)
Expanded array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Question 10 :- How to transpose the following array in NumPy?

 [[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [19]:
import numpy as np

array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)

transpose_array = np.transpose(np_array)
print("Transposed array:")
print(transpose_array)

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


Question 11 :- 11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
 Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1 ,
 + Index wise multiplicatio'
 + Matrix multiplicatio'
 + Add both the matricK
 + Subtract matrix B from 
 + Divide Matrix B by A




In [21]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Index-wise multiplication
index_wise_multiplication = A * B

# Addition
addition = A + B

# Subtraction
subtraction = A - B

# Division
division = B / A

print("Index-wise Multiplication:\n", index_wise_multiplication)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nDivision:\n", division)

Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Question 12 :- Which function in Numpy can be used to swap the byte order of an array?

In NumPy, you can use the byteswap() function to swap the byte order of an array. This function creates a new array with the byte order swapped.

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype=np.int32)

swapped_arr = arr.byteswap()

print("Array with byte order swapped:", swapped_arr)

Array with byte order swapped: [16777216 33554432 50331648 67108864]


Question 13 :- What is the significance of the np.linalg.inv function?

The np.linalg.inv function in NumPy is used to compute the multiplicative inverse of a square matrix. In other words, it calculates the inverse of a given matrix.

The significance of the np.linalg.inv function lies in its application to solve linear equations and systems of linear equations. Here are some key points about its significance:

1. Solving Linear Equations: The inverse of a matrix is used to solve systems of linear equations of the form Ax = B, where A is the coefficient matrix, x is the vector of variables, and B is the constant vector. The solution to the system can be found by multiplying both sides of the equation by the inverse of A: x = A^(-1) * B.

2. Matrix Operations: The inverse of a matrix is essential in various matrix operations, such as matrix multiplication, matrix division, and finding the determinant of a matrix.

3. Numerical Stability: In some cases, solving a system of linear equations directly may not be numerically stable, especially when dealing with ill-conditioned matrices. However, using the inverse of the matrix can sometimes provide a more stable solution.

Question 14 :- What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reshape a given array into a new shape specified by the user, as long as the total number of elements remains the same.

Here's what np.reshape does and how it's used:

1. Reshaping: The np.reshape function changes the shape of the array while preserving the order of its elements. It rearranges the elements of the array to fit into the new shape specified by the user.

2. Data Preservation: Importantly, np.reshape does not change the underlying data of the array. It merely changes the view of how the data is interpreted.

3. Flexible Usage: You can reshape arrays into various shapes, as long as the total number of elements remains constant. For example, you can reshape a 1D array into a 2D array, or vice versa.

4. syntax :-

np.reshape(array, new_shape)


Question 15 :- What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined and operated on together. It enables arithmetic operations to be performed between arrays of different shapes without the need for them to have the same shape or size. Broadcasting can significantly simplify and optimize code by eliminating the need for explicit loops.

In [23]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([10, 20, 30])

result = A + B

print("Array A:")
print(A)
print("\nArray B:")
print(B)
print("\nResult of Broadcasting:")
print(result)

Array A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array B:
[10 20 30]

Result of Broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
